### ISSUE TITLE
Harvested blocks don't show when changing hosts

### ISSUE THREAD

**Issue by Stoner19** [NewEconomyMovement/NemCommunityClient#395] opened 2015-04-16 03:11 UTC
When I stop delegated harvesting and switch to local harvesting via localhost the blocks harvested through my connection to KathrynJaneway.nemtrader.com no longer show on the "harvest blocks" page, although my full XEM balance is still correct.

**Comment by patmast3r** [comment] 2015-05-02 08:49
are you sure the NIS you changed to was fully synced at the time ?

**Comment by Jaguar0625** [comment] 2015-05-19 21:17
Duplicate of #383

**Closed by Jaguar0625** 2015-05-19 21:17 UTC
