### ISSUE TITLE
Bug showing Harvested blocks

### ISSUE THREAD

**Issue by filchef** [NewEconomyMovement/NemCommunityClient#383] opened 2015-04-07 16:32 UTC
http://i.imgur.com/WaMis80.jpg
This happened when I from settings switch over NIS from remote server to localhost.
This was version 0.6.25 also the same happened with version 6.0.26
![harvested blocks bug](https://cloud.githubusercontent.com/assets/6907969/7032245/15c74658-dd7a-11e4-8a63-a5c737b1f533.jpg)

**Comment by filchef** [comment] 2015-04-13 16:43
There is more one bug I find - when I use remote host he show all harvested blocks but when I use localhost he show just few blocks so I try to reload blockchain but now show  less blocks from before 
![harvested blocks bug1](https://cloud.githubusercontent.com/assets/6907969/7120347/4d7b63d2-e215-11e4-90fd-d05f2b4de382.jpg)

![harvested blocks bug2](https://cloud.githubusercontent.com/assets/6907969/7120354/6513f6bc-e215-11e4-9687-2a9e56237740.jpg)

**Comment by fyahfox** [comment] 2015-04-13 17:20
Not sure if this is related to #390, but I also have issues with the harvested blocks list.

Switching to another remote NIS via Settings leads to different results for that list and the calculated sum for the last 25 blocks, and switching accounts back and forth leads to different results as well.

Generally it can happen that block heights are disaplyed (and calculated) 2 times, but that is not the only problem:
![harvested_blocks_list](https://cloud.githubusercontent.com/assets/6625264/7121056/0c278ab2-e212-11e4-8e42-29083e0a7f58.PNG)

**Comment by filchef** [comment] 2015-04-13 21:16
Yes I think it  is not only problem - I hope problem is not in the blockchain

**Comment by BloodyRookie** [comment] 2015-05-19 19:54
We have found the cause for the problem. It will be fixed in the next version though it will be necessary to download the chain again (or download a recent db from bob). More details will be in the next release notes.

**Closed** 2015-05-19 21:17 UTC
Labels: bug
