### ISSUE TITLE
I still cant copy the Nem address to clipboard

### ISSUE THREAD

**Issue by Pinhais** [NewEconomyMovement/NemCommunityClient#205] opened 2014-11-20 10:17 UTC
Hi there.

On fireFox V 32 windows 8.1 64 I cant copy the Nem Address to clipboard. 

even on firefox on linux 64 bit I cant copy to clipboard.

I discoverd yesterday cause I needed to change some settings for my bot.

=)

**Comment by Pinhais** [comment] 2015-01-10 14:17
I still see this problem at the FireFox V34. I have tested with the exclusion of all the possible addons. When the mouse goes up the text, it get "like selected", as the photo above.

**Comment by Qrysto** [comment] 2015-01-10 14:58
Really weird, copy to clipboard on FF has never been not working for me. This "copy to clipboard" plugin needs Flash player, not sure if it's the cause. Is there a Flash extension active on your FF?

**Comment by Pinhais** [comment] 2015-01-21 10:27
No. Im pretty sure there is no flash installed on my computer and there is no plugin for it. 
I used the option "Disable all plugins" from the browser, turning firefox on a brand new installation (with no plugins except those normally installed).
This test returned the same result. It does not copy the wallet's information to the clipboard .
=(

**Comment by fyahfox** [comment] 2015-01-21 11:19
@Pinhais
If the Flash player is needed to do the "copy to clipboard" then of course it won't work if you disable it.

But it would be nice if it worked without Flash. Is there a way to do this?

**Comment by Qrysto** [comment] 2015-01-23 12:07
@fyahfox I'm afraid the answer is no. Most of browsers don't allow js code to access the clipboard for security concerns. Have a look at this http://stackoverflow.com/questions/6355300/copy-to-clipboard-without-flash

**Comment by Pinhais** [comment] 2015-02-01 13:22
Isnt is possible to make it in native Java 8?

I think this functions should be able to work without any kind of plugin. 

I wont install flash again on my computer. 

I found this: 

http://www.javapractices.com/topic/TopicAction.do?Id=82

http://stackoverflow.com/questions/3591945/copying-to-clipboard-in-java

i'm noit sure if this helps, as i dont understand a lot of programation.

Good luck. You can close the issue, if you want.

I just think it should be listed on a "fast guide help" or something like this.

**Comment by gimer** [comment] 2015-02-01 15:47
? @Pinhais web interface is pure html + js o0 how would you lire to fit java there :)

**Comment by Jaguar0625** [comment] 2015-03-12 02:35
Closing.

**Closed by Jaguar0625** 2015-03-12 02:35 UTC
